name: Build -> Test -> Package -> Deploy 🚀
run-name: "Running for commit '${{ github.event.commits[0].message }}' on branch ${{ github.ref }}"
on: 
  push:
    branches:
      - main
      - garmin
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install -r dev_requirements.txt
      - run: python3 -m pytest tests
  Package:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: ls
        run: |
          ls -lah
      - name: Create Docker Container
        run: docker build -t step-stats .
      - name: Build lambda deployment zip
        run: docker run --name lambda_build step-stats
      - run: echo "This job's status is ${{ job.status }}."
      - name: Copy deployment out of docker container
        run: docker cp lambda_build:/build/deployment.zip .
      - uses: actions/upload-artifact@master
        with:
          name: deployment.zip
          path: ./deployment.zip
  Deploy:
      runs-on: ubuntu-latest
      needs: Package
      steps:
      - uses: actions/download-artifact@master
        with:
          name: deployment.zip
          path: ./package
      - name: ls
        run: |
          ls -lahR
      - uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: garminDataUpdater
          zip_file: ./package/deployment.zip
