name: Build -> Test -> Package -> Deploy 🚀
run-name: "Running for commit '${{ github.event.commits[0].message }}' on branch ${{ github.ref }}"
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install -r dev_requirements.txt
      - run: python3 -m pytest tests
  Package:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: ls
        run: |
          ls -lah
      - name: Create virtualenv
        run: |
          pip3 install virtualenv && python3 -m venv . && source bin/activate
      - name: Build lambda deployment zip
        run: ./build.sh
      - run: echo "This job's status is ${{ job.status }}."
      - name: ls
        run: |
          ls -lah
      - uses: actions/upload-artifact@master
        with:
          name: deployment.zip
          path: ./deployment.zip
  Deploy:
      runs-on: ubuntu-latest
      needs: Package
      steps:
      - uses: actions/download-artifact@master
        with:
          name: deployment.zip
          path: ./package
      - name: ls
        run: |
          ls -lahR
      - uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: fitBitDataUpdater
          zip_file: ./package/deployment.zip
          dry_run: true
